version: "3.9"

services:
  testexp:
    depends_on:
      - keycloak
    restart: unless-stopped
    container_name: testexp
    network_mode: "host"
    build:
      dockerfile: TesteXP.Dockerfile
      context: ./
  
  rw_email:
    container_name: rw_email
    network_mode: "host"
    build:
      dockerfile: RW_Email.Dockerfile
      context: ./
    restart: unless-stopped

  mysql_xp:
    container_name: mysql_xp
    image: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root!"
    restart: unless-stopped

  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql_xp
        DB_DATABASE: keycloak
        DB_USER: root
        DB_PASSWORD: root!
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        PROXY_ADDRESS_FORWARDING: 'true'
      depends_on:
        - mysql_xp
      ports:
        - "4000:8080"
      volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      entrypoint: ["/wait-for-it.sh", "mysql_xp:3306", "--timeout=120", "--", "sh", "-c", "/opt/jboss/tools/docker-entrypoint.sh"]
      restart: unless-stopped

networks: 
  default: 
    name: xp-nt